# Generated by Django 3.1.7 on 2022-03-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsApp', '0006_auto_20220321_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('HEALTH', 'Здоровье'), ('STUDY', 'Обучение'), ('FINANCE', 'Финансы'), ('DOCUMENTS', 'Документы')], max_length=300, null=True),
        ),
    ]
