# Generated by Django 3.1.7 on 2022-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsApp', '0007_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Здоровье', 'Здоровье'), ('Обучение', 'Обучение'), ('Финансы', 'Финансы'), ('Документы', 'Документы'), ('Другое', 'Другое')], max_length=300, null=True),
        ),
    ]
